// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {plan} from '../models';
import {store} from '../models';
import {bridge} from '../models';

export function ChooseCareerRoot():Promise<string>;

export function EndSession(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetBudgetStatus():Promise<workspace.Budget>;

export function GetMaterial(arg1:string):Promise<Array<workspace.Artifact>>;

export function GetPlan():Promise<plan.Plan>;

export function GetPosition(arg1:number):Promise<store.Position>;

export function GetReconciliation():Promise<Array<plan.Check>>;

export function GetTopics():Promise<Array<plan.Topic>>;

export function GetWorkspace():Promise<bridge.Workspace>;

export function ReadArtifact(arg1:number):Promise<workspace.Content>;

export function SavePosition(arg1:number,arg2:number):Promise<void>;

export function SetCareerRoot(arg1:string):Promise<void>;

export function StartSession(arg1:string,arg2:string):Promise<number>;

export function TickItem(arg1:string,arg2:boolean):Promise<void>;

export function WriteArtifact(arg1:number,arg2:string):Promise<void>;
