// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {plan} from '../models';
import {bridge} from '../models';

export function ChooseCareerRoot():Promise<string>;

export function GetMaterial(arg1:string):Promise<Array<workspace.Artifact>>;

export function GetPlan():Promise<plan.Plan>;

export function GetReconciliation():Promise<Array<plan.Check>>;

export function GetTopics():Promise<Array<plan.Topic>>;

export function GetWorkspace():Promise<bridge.Workspace>;

export function ReadArtifact(arg1:number):Promise<workspace.Content>;

export function SetCareerRoot(arg1:string):Promise<void>;

export function TickItem(arg1:string,arg2:boolean):Promise<void>;

export function WriteArtifact(arg1:number,arg2:string):Promise<void>;
