// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseCareerRoot() {
  return window['go']['bridge']['App']['ChooseCareerRoot']();
}

export function GetMaterial(arg1) {
  return window['go']['bridge']['App']['GetMaterial'](arg1);
}

export function GetPlan() {
  return window['go']['bridge']['App']['GetPlan']();
}

export function GetReconciliation() {
  return window['go']['bridge']['App']['GetReconciliation']();
}

export function GetTopics() {
  return window['go']['bridge']['App']['GetTopics']();
}

export function GetWorkspace() {
  return window['go']['bridge']['App']['GetWorkspace']();
}

export function ReadArtifact(arg1) {
  return window['go']['bridge']['App']['ReadArtifact'](arg1);
}

export function SetCareerRoot(arg1) {
  return window['go']['bridge']['App']['SetCareerRoot'](arg1);
}

export function TickItem(arg1, arg2) {
  return window['go']['bridge']['App']['TickItem'](arg1, arg2);
}

export function WriteArtifact(arg1, arg2) {
  return window['go']['bridge']['App']['WriteArtifact'](arg1, arg2);
}
